BubblehopWeb/Models/Destination.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BubblehopWeb.Models
{
    public class Destination
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string LocationName { get; set; }

        public DateTime ArrivalDate { get; set; }

        public string? Activity { get; set; }

        public int TravelPlanId { get; set; }
        [ForeignKey("TravelPlanId")]
        public TravelPlan TravelPlan { get; set; }
    }
}

BubblehopWeb/Models/ErrorViewModel.cs
namespace BubblehopWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BubblehopWeb/Models/TravelPlan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.InteropServices.Marshalling;

namespace BubblehopWeb.Models
{
    public class TravelPlan
    {
        [Key]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "Please enter the name of your trip")]
        [Display(Name = "Trip name")]
        public string PlanName { get; set; }

        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        public string? Description { get; set; }

        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }

        [Required(ErrorMessage = "Please enter your destination")]
        public ICollection<Destination> Destinations { get; set; }
        public ICollection<UserTravelPlan>? UserTravelPlans { get; set; }
    }
}

BubblehopWeb/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace BubblehopWeb.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string Email { get; set; }

        public ICollection<UserTravelPlan>? UserTravelPlans { get; set; }
    }
}

BubblehopWeb/Models/UserTravelPlan.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace BubblehopWeb.Models
{
    public class UserTravelPlan
    {
        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }


        public int TravelPlanId { get; set; }
        [ForeignKey("TravelPlanId")]
        public TravelPlan TravelPlan { get; set; }
    }
}

BubblehopWeb/Areas/User/Controllers/HomeController.cs
using Bubblehop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BubblehopWeb.Areas.User.Controllers
{
    [Area("User")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BubblehopWeb/Areas/User/Controllers/TravelPlanController.cs
using Bubblehop.DataAccess.DataRepository.RepositoryInterface;
using Bubblehop.Models;
using Microsoft.AspNetCore.Mvc;

namespace BubblehopWeb.Areas.User.Controllers
{
    [Area("User")]
    public class TravelPlanController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TravelPlanController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreatePlan()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePlan(TravelPlan plan)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.TravelPlan.AddWithAsync(plan);
            }

            return View();
        }
    }
}

BubblehopWeb/Controllers/HomeController.cs
using BubblehopWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BubblehopWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BubblehopWeb/Areas/User/Views/Home/Index.cshtml
<p1>Welcom to Bubblehop</p1>

BubblehopWeb/Areas/User/Views/TravelPlan/CreatePlan.cshtml
@model TravelPlan


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-content">

                <!-- ***** Plan form ***** -->
                <div class="gaming-library">
                    <div class="col-lg-12">
                        <div class="heading-section">
                            <h4>Let's go!</h4>
                        </div>

                        <div>
                            <form method="post" class="form-floating">
                                <div class="form-floating mb-3">
                                    <input asp-for="PlanName" class="form-control" id="PlanName">
                                    <label asp-for="PlanName"></label>
                                    <span asp-validation-for="PlanName"></span>
                                </div>

                                <div class="form-floating mb-3">
                                    <input asp-for="StartDate" class="form-control" id="StartDate">
                                    <label asp-for="StartDate"></label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input asp-for="EndDate" class="form-control" id="EndDate">
                                    <label asp-for="EndDate"></label>
                                </div>

                                <div class="form-floating mb-3">
                                    <input asp-for="Description" class="form-control" id="Description">
                                    <label asp-for="Description"></label>
                                </div>

                                <!-- ***** Destination Start ***** -->
                                <div class="gaming-library">
                                    <div class="col-lg-12">
                                        <div class="my-heading my-heading-container mb-3">
                                            <h4>Your destination</h4>
                                            <button class="my-add-button">Add a destination</button>
                                        </div>
                                        <div class="item">
                                            <ul>
                                                <li><img src="assets/images/game-01.jpg" alt="" class="templatemo-item"></li>
                                                <li><h4>Dota 2</h4><span>Sandbox</span></li>
                                                <li><h4>Date Added</h4><span>24/08/2036</span></li>
                                                <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
                                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
                                            </ul>
                                        </div>
                                        <div class="item">
                                            <ul>
                                                <li><img src="assets/images/game-02.jpg" alt="" class="templatemo-item"></li>
                                                <li><h4>Fortnite</h4><span>Sandbox</span></li>
                                                <li><h4>Date Added</h4><span>22/06/2036</span></li>
                                                <li><h4>Hours Played</h4><span>740 H 52 Mins</span></li>
                                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                                <li><div class="main-border-button"><a href="#">Donwload</a></div></li>
                                            </ul>
                                        </div>
                                        <div class="item last-item">
                                            <ul>
                                                <li><img src="assets/images/game-03.jpg" alt="" class="templatemo-item"></li>
                                                <li><h4>CS-GO</h4><span>Sandbox</span></li>
                                                <li><h4>Date Added</h4><span>21/04/2036</span></li>
                                                <li><h4>Hours Played</h4><span>892 H 14 Mins</span></li>
                                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- ***** Destination End ***** -->
                                <!-- ***** Button Start ***** -->
                                <div class="mt-5 my-button-container-flex-end">

                                    <a asp-area="User" asp-controller="TravelPlan" asp-action="Index" class="my-outline-button-back">
                                        Back
                                    </a>

                                    <button class="my-button" type="submit">Create a travel plan</button>

                                </div>
                                <!-- ***** Button End ***** -->
                            </form>
                        </div>


                    </div>

                </div>
                <!-- ***** Plan Form End ***** -->


            </div>
        </div>
    </div>
</div>




<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="~/cyborg-1.0.0/vendor/jquery/jquery.min.js"></script>
<script src="~/cyborg-1.0.0/vendor/bootstrap/js/bootstrap.min.js"></script>

<script src="~/cyborg-1.0.0/assets/js/isotope.min.js"></script>
<script src="~/cyborg-1.0.0/assets/js/owl-carousel.js"></script>
<script src="~/cyborg-1.0.0/assets/js/tabs.js"></script>
<script src="~/cyborg-1.0.0/assets/js/popup.js"></script>
<script src="~/cyborg-1.0.0/assets/js/custom.js"></script>

BubblehopWeb/Areas/User/Views/TravelPlan/Index.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-content">

                <!-- ***** Banner Start ***** -->
                <div class="main-banner">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="header-text">
                                <h6>Go explore !</h6>
                                <h4><em>The world is a book,</em> and those who do not travel read only one page.</h4>
                                <div class="main-button">
                                    <a asp-area="User" asp-controller="TravelPlan" asp-action="CreatePlan">Plan your trip</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ***** Banner End ***** -->

                <!-- ***** Most Popular Start ***** -->
                <div class="most-popular">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="heading-section">
                                <h4>Your Travel Plans</h4>
                            </div>
                            <div class="row">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-01.jpg" alt="">
                                        <h4>Fortnite<br><span>Sandbox</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-02.jpg" alt="">
                                        <h4>PubG<br><span>Battle S</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-03.jpg" alt="">
                                        <h4>Dota2<br><span>Steam-X</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-04.jpg" alt="">
                                        <h4>CS-GO<br><span>Legendary</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="item">
                                        <div class="row">
                                            <div class="col-lg-6 col-sm-6">
                                                <div class="item inner-item">
                                                    <img src="assets/images/popular-05.jpg" alt="">
                                                    <h4>Mini Craft<br><span>Legendary</span></h4>
                                                    <ul>
                                                        <li><i class="fa fa-star"></i> 4.8</li>
                                                        <li><i class="fa fa-download"></i> 2.3M</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6">
                                                <div class="item">
                                                    <img src="assets/images/popular-06.jpg" alt="">
                                                    <h4>Eagles Fly<br><span>Matrix Games</span></h4>
                                                    <ul>
                                                        <li><i class="fa fa-star"></i> 4.8</li>
                                                        <li><i class="fa fa-download"></i> 2.3M</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-07.jpg" alt="">
                                        <h4>Warface<br><span>Max 3D</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-sm-6">
                                    <div class="item">
                                        <img src="assets/images/popular-08.jpg" alt="">
                                        <h4>Warcraft<br><span>Legend</span></h4>
                                        <ul>
                                            <li><i class="fa fa-star"></i> 4.8</li>
                                            <li><i class="fa fa-download"></i> 2.3M</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="main-button">
                                        <a href="browse.html">View Your Plans</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ***** Most Popular End ***** -->

                <!-- ***** Gaming Library Start ***** -->
                <div class="gaming-library">
                    <div class="col-lg-12">
                        <div class="heading-section">
                            <h4>You Join The Journey</h4>
                        </div>
                        <div class="item">
                            <ul>
                                <li><img src="assets/images/game-01.jpg" alt="" class="templatemo-item"></li>
                                <li><h4>Dota 2</h4><span>Sandbox</span></li>
                                <li><h4>Date Added</h4><span>24/08/2036</span></li>
                                <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
                            </ul>
                        </div>
                        <div class="item">
                            <ul>
                                <li><img src="assets/images/game-02.jpg" alt="" class="templatemo-item"></li>
                                <li><h4>Fortnite</h4><span>Sandbox</span></li>
                                <li><h4>Date Added</h4><span>22/06/2036</span></li>
                                <li><h4>Hours Played</h4><span>740 H 52 Mins</span></li>
                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                <li><div class="main-border-button"><a href="#">Donwload</a></div></li>
                            </ul>
                        </div>
                        <div class="item last-item">
                            <ul>
                                <li><img src="assets/images/game-03.jpg" alt="" class="templatemo-item"></li>
                                <li><h4>CS-GO</h4><span>Sandbox</span></li>
                                <li><h4>Date Added</h4><span>21/04/2036</span></li>
                                <li><h4>Hours Played</h4><span>892 H 14 Mins</span></li>
                                <li><h4>Currently</h4><span>Downloaded</span></li>
                                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="main-button">
                            <a href="profile.html">View Your Join</a>
                        </div>
                    </div>
                </div>
                <!-- ***** Gaming Library End ***** -->
            </div>
        </div>
    </div>
</div>




<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="~/cyborg-1.0.0/vendor/jquery/jquery.min.js"></script>
<script src="~/cyborg-1.0.0/vendor/bootstrap/js/bootstrap.min.js"></script>

<script src="~/cyborg-1.0.0/assets/js/isotope.min.js"></script>
<script src="~/cyborg-1.0.0/assets/js/owl-carousel.js"></script>
<script src="~/cyborg-1.0.0/assets/js/tabs.js"></script>
<script src="~/cyborg-1.0.0/assets/js/popup.js"></script>
<script src="~/cyborg-1.0.0/assets/js/custom.js"></script>

BubblehopWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="~/BubblehopWeb.styles.css" asp-append-version="true" />

        <title>Bubblehop</title>

        <!-- Bootstrap core CSS -->
        <link href="~/cyborg-1.0.0/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="~/cyborg-1.0.0/assets/css/fontawesome.css">
        <link rel="stylesheet" href="~/cyborg-1.0.0/assets/css/templatemo-cyborg-gaming.css">
        <link rel="stylesheet" href="~/cyborg-1.0.0/assets/css/owl.css">
        <link rel="stylesheet" href="assets/css/animate.css">
        <link rel="stylesheet" href="~/cyborg-1.0.0/assets/css/animate.css">
        <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

        <link rel="stylesheet" href="~/css/site.css" />

    </head>

    <body>

        <!-- ***** Preloader Start ***** -->
        <div id="js-preloader" class="js-preloader">
            <div class="preloader-inner">
                <span class="dot"></span>
                <div class="dots">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
        </div>
        <!-- ***** Preloader End ***** -->
        <!-- ***** Header Area Start ***** -->
        <header class="header-area header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="main-nav">

                            <!-- ***** Logo Start ***** -->
                            <a href="index.html" class="logo">
                                <img src="~/cyborg-1.0.0/assets/images/logo.png" alt="">
                            </a>
                            <!-- ***** Logo End ***** -->

                            <!-- ***** Search End ***** -->
                            <div class="search-input">
                                <form id="search" action="#">
                                    <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                                    <i class="fa fa-search"></i>
                                </form>
                            </div>
                            <!-- ***** Search End ***** -->

                            <!-- ***** Menu Start ***** -->
                            <ul class="nav">
                                <li><a asp-area="User" asp-controller="Home" asp-action="Index" class="active">Home</a></li>
                                <li><a asp-area="User" asp-controller="TravelPlan" asp-action="Index">Travel plans</a></li>
                                <li><a href="details.html">Details</a></li>
                                <li><a href="streams.html">Streams</a></li>
                                <li><a href="profile.html">Profile <img src="assets/images/profile-header.jpg" alt=""></a></li>
                            </ul>
                            <a class='menu-trigger'>
                                <span>Menu</span>
                            </a>
                            <!-- ***** Menu End ***** -->
                        </nav>
                    </div>
                </div>
            </div>
        </header>
        <!-- ***** Header Area End ***** -->


        <div class="container">
            <main role="main" class="pb-3">              
                @RenderBody()
            </main>
        </div>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p>
                            Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved.

                            <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a>  Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </p>
                    </div>
                </div>
            </div>
        </footer>


        <!-- Scripts -->
        <!-- Bootstrap core JavaScript -->
        <script src="~/cyborg-1.0.0/vendor/jquery/jquery.min.js"></script>
        <script src="~/cyborg-1.0.0/vendor/bootstrap/js/bootstrap.min.js"></script>

        <script src="~/cyborg-1.0.0/assets/js/isotope.min.js"></script>
        <script src="~/cyborg-1.0.0/assets/js/owl-carousel.js"></script>
        <script src="~/cyborg-1.0.0/assets/js/tabs.js"></script>
        <script src="~/cyborg-1.0.0/assets/js/popup.js"></script>
        <script src="~/cyborg-1.0.0/assets/js/custom.js"></script>


    </body>

</html>